2020-12-24 09:37:20,279 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:86]
2020-12-24 09:43:26,269 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:86]
2020-12-24 09:43:40,115 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:86]
2020-12-24 09:50:30,620 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:86]
2020-12-24 12:50:19,836 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 12:50:19,836 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 12:50:19,836 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 12:50:19,836 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:03:23,864 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:03:23,864 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:03:23,883 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:03:23,888 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:18,900 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:18,926 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:18,946 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:19,043 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:19,086 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:19,087 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:19,101 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:19,123 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:19,124 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:19,138 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:19,145 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:13:19,162 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 16:39:12,149 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 17:17:12,857 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 17:18:26,430 ERROR: Exception on /api/vue-element-admin/tokens/ [POST] [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask_httpauth.py", line 149, in decorated
    user = self.authenticate(auth, password)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask_httpauth.py", line 220, in authenticate
    return self.verify_password_callback(username, client_password)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/api/auth.py", line 18, in verify_password
    print('sa',username, password)
OSError: [Errno 5] Input/output error
2020-12-24 17:18:31,356 ERROR: Exception on /api/vue-element-admin/tokens/ [POST] [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask_httpauth.py", line 149, in decorated
    user = self.authenticate(auth, password)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask_httpauth.py", line 220, in authenticate
    return self.verify_password_callback(username, client_password)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/api/auth.py", line 18, in verify_password
    print('sa',username, password)
OSError: [Errno 5] Input/output error
2020-12-24 17:19:31,746 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
2020-12-24 17:19:48,354 ERROR: Exception on /api/vue-element-admin/tokens/ [POST] [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask_httpauth.py", line 149, in decorated
    user = self.authenticate(auth, password)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/flask-env/lib/python3.8/site-packages/flask_httpauth.py", line 220, in authenticate
    return self.verify_password_callback(username, client_password)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/api/auth.py", line 23, in verify_password
    user.from_dict({"username":username,"password":password}, new_user=True)
  File "/Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/models.py", line 261, in from_dict
    if self.email in current_app.config['ADMINS']:
KeyError: 'ADMINS'
2020-12-24 17:20:40,796 INFO: Flask API Startup [in /Users/zhangbai/Desktop/vue-projects/flask-vue-sample/app/__init__.py:87]
